export default [
    {
      name: "Voice to Text",
      desc: "Aplicação simples que usa reconhecimento de voz para transformar a voz em texto",
      rep: "",
      nameFile: "voicerecognition",
      typeLinkText: "Link",
      toLink: true,
      link: "https://voice2totext.vercel.app",
    },
    {
      name: "Nexus-ui",
      desc: "Estou criando uma lib de componentes de para vuejs baseada em tailwindcss",
      rep: "",
      nameFile: "nexus",
      typeLinkText: "Link",
      toLink: true,
      link: "https://nexus-ui.gitbook.io/nexus-ui/",
    },
    {
      name: "n0d3rr Syntax Highlighter",
      desc: "é um editor de código cuja o objetivo é facilitar a escrita de documentações em exeplos de códigos",
      rep: "",
      nameFile: "NSH",
      typeLinkText: "Link",
      toLink: true,
      link: "https://n0d3rr-sh.vercel.app/#/",
    },
    {
      name: "Laravel course page",
      desc: "Este foi um freelancer que fiz, resumidamente uma pagina para um curso gratuito de laravel",
      rep: "",
      nameFile: "laravelCourse",
      typeLinkText: "Link",
      toLink: true,
      link: "https://cursolaravel.com.br/",
    },
    {
      name: "Turing Community",
      desc: "Uma comunidade de programação no discord para todos desfrutarem.",
      rep: "",
      nameFile: "turingCommunity",
      typeLinkText: "Link",
      toLink: true,
      link: "https://turingcommunity.vercel.app/",
    },
    {
      name: "TWvue",
      desc: "Plugin para vuejs baseados nos estilos do Tawildindcss.",
      rep: "twvue",
      nameFile: "twvue",
      typeLinkText: "Repositório",
      toLink: false,
    },
    {
      name: "PigApp",
      desc: "Um Projeto com a função de registar despesas e ganhos de dinheiro com a finalidade de obter um controle maior de tudo",
      rep: "PigApp",
      nameFile: "PigApp",
      typeLinkText: "Repositório",
      toLink: false,
    },
    {
      name: "Food List",
      desc: "Projeto feito para estudar as ultilidades do Vuex e como usar em projetos.",
      rep: "foodlist",
      nameFile: "food",
      typeLinkText: "Repositório",
      toLink: false,
    },
    {
      name: "Todo Redux",
      desc: "Projeto feito para estudar as ultilidades do Redux e como usar em projetos.",
      rep: "todo-redux",
      nameFile: "todo",
      typeLinkText: "Repositório",
      toLink: false,
    },
  ]